### ISSUE TITLE
CTPN train prototxt

### ISSUE THREAD

**Issue by TaoDream** [Xiangyu-CAS/caffe-model-gallery#1]
Hi, @Xiangyu-CAS 
I have seen that you have successfully trained your CTPN model in caffe framework.
I have implemented my own which failed to converge after adding LSTM layers.
Can you share your prototxt file with me. 

Thanks very much

**Comment by Xiangyu-CAS** [comment]
The prototxt have been uploaded, check it if you are interested, it seems you forget to initial weights of LSTM layers.

**Comment by TaoDream** [comment]
Thanks very much.  It seems that I indeed forget that. I am running your prototxt  file now. I am excited to get the desired result.
